### ISSUE TITLE
Texture to shiny

### ISSUE THREAD

**Issue by Artemisthemp** [EndlesNights/ApertureScienceWCDice#3]
The white texture is too shiny on 8.9 and 9.249.
![Bad texuture](https://user-images.githubusercontent.com/81526156/153715636-0d7f6eff-2f1a-42b2-9c1f-cf37ffaa6b78.png)

**Note:** I have already tried to uninstall the module and reinstall it.

**Comment by EndlesNights** [comment]
That appear to be something on Dice-SO-Nice side of things in their newest release. As a stop gap, you roll back to dice-so-nice v4.3.1 it should go back to normal. While I go investigate and see if I can patch this out.

 Manifest URL: https://gitlab.com/riccisi/foundryvtt-dice-so-nice/raw/4.3.1/module/module.json

**Comment by EndlesNights** [comment]
Issue should be fixed for the most part. Latest update to DsN added in support for emission shades, and my materials had a value incorrectly set, but as it was that was previously unused by DoS it went unnoticed until now.
 
I might do some model tweaks in the near future, but it should no longer be a ball of blinding light.
